---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-client-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: psql-client-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: psql-client-demo
    spec:
      containers:
        - image: centosadmin/psql-client-demo
          name: psql-client-demo
