---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-stable
  labels:
    app: myapp
data:
  default.conf: |
    server {
        listen       80 default_server;
        server_name  _;

        default_type text/plain;

        location / {
            return 200 'I am stable!\n';
        }
    }
