apiVersion: v1
kind: Pod
metadata:
  name: vault-console
  labels:
    app: vault-console
spec:
  containers:
  - name: valult
    image: vault
    command: ["sh", "-c", "echo going to sleep... && sleep 10000"]
    env:
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: vault-unseal-keys
          key: vault-root
    - name: VAULT_SKIP_VERIFY
      value: 'true'
    - name: VAULT_ADDR
      value: https://vault:8200
