kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system-psp
  namespace: default
roleRef:
  kind: ClusterRole
  name: system-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
