---
apiVersion: v1
kind: Namespace
metadata:
  name: red

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: red
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-storage
      mountPath: /data
  volumes:
  - name: redis-storage
    emptyDir: {}
