---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: system
  namespace: default
spec:
  privileged: true
  hostNetwork: true
  hostPID: true
  hostIPC: true
  hostPorts:
    - min: 0
      max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - '*'
  allowedCapabilities:
    - '*'
